---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Pull Docker Image
      docker_image:
        name: rahul0129/calculator
        tag: latest
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Run Docker Container
      docker_container:
        name: calculator-container
        image: rahul0129/calculator:latest
        state: started
        recreate: yes
        interactive: yes
        tty: yes
